import React from 'react';
import type { Metadata } from 'next';
// eslint-disable-next-line camelcase
import { Vina_Sans, SUSE_Mono } from 'next/font/google';
import './globals.css';

const vinaSans = Vina_Sans({
  variable: '--font-vina-sans',
  weight: '400',
});

const suseMono = SUSE_Mono({
  variable: '--font-suse-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${vinaSans.variable} ${suseMono.variable}`}>
        {children}
      </body>
    </html>
  );
}